# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f76b08fbdd04c8ce70934785bfb41f51d675fc2c532aba78d6993c3bf4dcc8cedaec61b2f63c12e450d418bfdaf7efa3bb01dd266a39dfc75d8c92e5f20e5a12

test:
  secret_key_base: 6a6d543b1284bb770de6cb797e6ced6e2247ad434df947e3c990ab5952fdefd442a06e1fd7c19bc1f2f9e2e8134a1e4b3334bdfc7343efe1330e04dc23668992

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
